name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:

jobs:
  full-build:
    runs-on: macOS-12
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: fullbuild.sh 
        run: ./fullbuild.sh
